name: Changed-files

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: tony84727/changed-file-filter@v0.2.0
      id: filter
      with:
        filters: |
          ibc:
            - 'contracts/javascore/ibc/**/*'
    - name: Print changed ibc files
      if: steps.filter.outputs.ibc == 'true'
      run: echo "Changed doc files: ${{ step.filter.outputs.ibc_files }}"