name: Build and Deploy Frontend
on:
  workflow_dispatch:
    inputs:
      root_ssh_pub_key:
        description: ssh public key - ubuntu
        required: true
        type: string
      deployr_ssh_pub_key:
        description: ssh public key - deployr
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: configureawscredentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_STS_ROLE }}
          role-session-name: cicd
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform Apply
        id:   apply
        env:
          TF_VAR_root_ssh_pub_key:  "${{ github.event.inputs.root_ssh_pub_key }}"
          TF_VAR_deployr_ssh_pub_key: "${{ github.event.inputs.deployr_ssh_pub_key }}"
          TF_VAR_vpc_id: "${{ env.VPC_ID }}"
          TF_VAR_subnet_id: "${{ env.SUBNET_ID }}"
        run: |
          echo "$TF_VAR_root_ssh_pub_key, $TF_VAR_deployr_ssh_pub_key, $TF_VAR_vpc_id, $TF_VAR_subnet_id"
          cd .github/deployer
          echo "$TF_VAR_root_ssh_pub_key" > id_rsa.pub
          export TF_VAR_root_ssh_pub_key="${{ github.event.inputs.root_ssh_pub_key }}"
          terraform init
          terraform validate
          terraform plan 
          terraform apply -auto-approve

