on:
  workflow_call:
    outputs:
      label: ${{ jobs.runner.start.outputs.label }}
      ec2-instance-id: ${{ jobs.runner-start.start.outputs.ec2-instance-id }}
jobs:
  runner-start:
    name: Start runner
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Get aws ami id built by packer
        id: ami-id
        run: |
          ami_id=$(aws ec2 describe-images \
            --filters "Name=tag:Name,Values=github-runner" "Name=tag:Project,Values=IBC" "Name=tag:ManagedBy,Values=Packer" \
            --query 'Images[*].[ImageId]' \
            --output text --max-items 1)
          echo "AMI_ID=$ami_id" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v3
      - name: Start EC2 instance
        id: start
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ec2-image-id: ${{ steps.ami-id.outputs.AMI_ID }}
          ec2-instance-type: c5.2xlarge
          subnet-id: subnet-f1fcd4df
          security-group-id: sg-03cb8034e27e1caeb
          aws-resource-tags: >
            [
              {"Key": "Name", "Value": "ec2-github-runner"},
              {"Key": "Repository", "Value": "${{ github.repository }}"},
              {"Key": "Project", "Value": "IBC"}
            ]
          pre-runner-script: |
            #!/bin/sh
            docker build -t relayer --build-args VERSION=0.1.0-alpha.7 .
